# Funding options for Smart Room Manager
# You can add funding options here if you want to accept donations

# github: [GevaudanBeast]
# patreon: your-patreon-username
# ko_fi: your-ko-fi-username
# buy_me_a_coffee: your-buymeacoffee-username
# custom: ["https://your-donation-link.com"]
